name: Generate Snake
on:
  schedule:
    - cron: "0 */12 * * *" # Every 12 hours
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v2

      # Step 2: Generate the snake animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: mohamedabdelhamed0 # Your GitHub username
          svg_out_path: dist/github-contribution-grid-snake-dark.svg # Output file path
          snake_color: 'blue'

      # Step 3: Publish the animation to the `output` branch
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
